export { HomeView } from "./home";
export { TemplateView } from "./template";
export { AccountView } from "./account";
export { TemplateSchemaView } from "./templateSchema";
export { ObjectView } from "./object";
export { PlayView } from "./play";
export { GameView } from "./game";
export { StoreView } from "./store";
export { SolitaryView } from "./solitary";